version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    commit-message:
      prefix: "chore"
      include: "scope"
